---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangz.
--- DateTime: 2024/9/28 11:36
---
local voucherId = ARGV[1]
-- 1.2.用户id
local userId = ARGV[2]
-- 1.3.订单id
local orderId = ARGV[3]

--
-- 2.数据key
-- 2.1.库存key .. 是lua脚本的连接字符
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2.订单key
local orderKey = 'seckill:order:' .. voucherId

-- 库存不足
if(tonumber(redis.call('get',stockKey))<=0) then
    return 1
end

--订单是否重复,由于这里不需要判断大小,只需要判断是否相等所以这里只需要
if(redis.call('sismember',orderKey,userId) ==1) then
    return 2
end

-- 扣减库存
redis.call('incrby',stockKey,-1)

-- 往订单里面添加
redis.call('sadd',orderKey,userId)

--往消息队列里面添加
redis.call('xadd','stream.order','*','userId',userId,'voucherId',voucherId,'id',orderId)

return 0;